// SPDX-License-Identifier: GPL-3.0-or-later

// Command cask writes the Homebrew cask for the release in build/.
//
//	go run ./cmd/cask
//	go run ./cmd/cask --check
//
// The version comes from VERSION and the checksum from the package that
// `make pkg-notarized` produced, so the cask can only ever describe a release
// that was actually built here. --check also asks the download URL whether
// that release is published yet, which is the one thing this cannot know from
// the files on disk.
//
// Written rather than hand-edited because the two fields that matter — the
// version and the checksum — have to agree with each other and with what is
// on the CDN. A cask whose checksum is one release behind fails at install
// time with a mismatch nobody can act on.
package main

import (
	"crypto/sha256"
	"encoding/hex"
	"flag"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

const caskTemplate = `# Generated by ` + "`make cask`" + `. Edit the generator, not this file: the version and
# the checksum have to match a release that is actually published, and a hand
# edit is how those two drift apart.
cask "mymicrotunnel" do
  version "{{ .Version }}"
  sha256 "{{ .Checksum }}"

  url "{{ .BaseURL }}/MyMicroTunnel-#{version}.pkg"
  name "MyMicroTunnel"
  desc "Publishes a local port at a hostname you own, over WireGuard to AWS"
  homepage "{{ .Homepage }}"

  # The same feed the app's own updater reads, so brew and the app never
  # disagree about what the current version is.
  livecheck do
    url "{{ .FeedURL }}"
    strategy :sparkle
  end

  auto_updates true
  depends_on macos: :ventura

  pkg "MyMicroTunnel-#{version}.pkg"

  uninstall launchctl: "ca.maragato.mymicrotunnel.supervisor",
            quit:      "ca.maragato.mymicrotunnel-menubar",
            pkgutil:   "ca.maragato.mymicrotunnel",
            delete:    [
              "/etc/sudoers.d/mymicrotunnel",
              "/Library/LaunchDaemons/ca.maragato.mymicrotunnel.supervisor.plist",
              "/Library/PrivilegedHelperTools/ca.maragato.mymicrotunnel.helper",
              "/usr/local/bin/mymicrotunnel",
              "/usr/local/lib/mymicrotunnel",
            ]

  # Deliberately not removed by ` + "`uninstall`" + `: the profiles name deployments that
  # exist in an AWS account and cost money, and /etc/wireguard holds the
  # private key those deployments trust. Taking either away on a plain
  # uninstall would leave a stack nothing on this Mac can reach, still running.
  #
  # ` + "`brew uninstall --zap`" + ` is the explicit ask for that, and even then the AWS
  # side has to go first: run ` + "`mymicrotunnel uninstall`" + ` while the profiles are
  # still here.
  zap delete: "/etc/wireguard",
      trash:  [
        "~/Library/Application Support/MyMicroTunnel",
        "~/Library/Caches/ca.maragato.mymicrotunnel-menubar",
        "~/Library/Preferences/ca.maragato.mymicrotunnel-menubar.plist",
      ]

  caveats <<~EOS
    MyMicroTunnel deploys AWS resources into your own account, which cost
    roughly USD 26/month while a gateway is running. Open the menu bar icon
    and choose Setup to deploy one.

    Before uninstalling, run ` + "`mymicrotunnel uninstall`" + ` so the AWS side goes
    with it. Removing the app alone leaves the stack running and billing.
  EOS
end
`

type cask struct {
	Version  string
	Checksum string
	BaseURL  string
	FeedURL  string
	Homepage string
}

func main() {
	baseURL := flag.String("base-url", envOr("APPCAST_BASE_URL", "https://downloads.maragato.ca/releases"),
		"where the packages are published")
	feedURL := flag.String("feed-url", envOr("APPCAST_FEED_URL", "https://downloads.maragato.ca/appcast.xml"),
		"the appcast brew reads for new versions")
	homepage := flag.String("homepage", "https://mymicrotunnel.maragato.ca/", "the product page")
	check := flag.Bool("check", false, "also ask the download URL whether this release is published")
	flag.Parse()

	root := repoRoot()
	version := strings.TrimSpace(readFile(filepath.Join(root, "VERSION")))
	packagePath := filepath.Join(root, "build", fmt.Sprintf("MyMicroTunnel-%s.pkg", version))

	sum, err := checksum(packagePath)
	if err != nil {
		fail("%v\n\n  Build it first: make pkg-notarized PROFILE=<profile>", err)
	}

	out := filepath.Join(root, "packaging", "homebrew", "mymicrotunnel.rb")
	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		fail("%v", err)
	}
	file, err := os.Create(out)
	if err != nil {
		fail("%v", err)
	}
	defer file.Close()

	body := template.Must(template.New("cask").Parse(caskTemplate))
	if err := body.Execute(file, cask{
		Version:  version,
		Checksum: sum,
		BaseURL:  strings.TrimSuffix(*baseURL, "/"),
		FeedURL:  *feedURL,
		Homepage: *homepage,
	}); err != nil {
		fail("%v", err)
	}
	fmt.Printf("  ✓ %s describes %s\n", out, version)

	if !*check {
		fmt.Printf("\n  Publish the release first, then copy this into the tap:\n")
		fmt.Printf("    %s/Casks/mymicrotunnel.rb\n", "homebrew-mymicrotunnel")
		return
	}

	url := fmt.Sprintf("%s/MyMicroTunnel-%s.pkg", strings.TrimSuffix(*baseURL, "/"), version)
	response, err := http.Head(url)
	if err != nil {
		fail("Could not reach %s: %v", url, err)
	}
	defer response.Body.Close()
	if response.StatusCode != http.StatusOK {
		fail("%s answers %s.\n\n"+
			"  The cask names a release that is not published yet; run make publish first.",
			url, response.Status)
	}
	fmt.Printf("  ✓ %s is published\n", url)
}

// checksum is what brew verifies the download against, so it is read from the
// package itself rather than from anything that describes it.
func checksum(path string) (string, error) {
	file, err := os.Open(path)
	if err != nil {
		return "", fmt.Errorf("reading the package: %w", err)
	}
	defer file.Close()

	digest := sha256.New()
	if _, err := io.Copy(digest, file); err != nil {
		return "", err
	}
	return hex.EncodeToString(digest.Sum(nil)), nil
}

func repoRoot() string {
	directory, err := os.Getwd()
	if err != nil {
		fail("%v", err)
	}
	for {
		if _, err := os.Stat(filepath.Join(directory, "go.mod")); err == nil {
			return directory
		}
		parent := filepath.Dir(directory)
		if parent == directory {
			fail("Not inside the repository: no go.mod above %s", directory)
		}
		directory = parent
	}
}

func readFile(path string) string {
	content, err := os.ReadFile(path)
	if err != nil {
		fail("%v", err)
	}
	return string(content)
}

func envOr(name, fallback string) string {
	if value := os.Getenv(name); value != "" {
		return value
	}
	return fallback
}

func fail(format string, arguments ...any) {
	fmt.Fprintf(os.Stderr, "✗ "+format+"\n", arguments...)
	os.Exit(1)
}
